config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/' => 'main#dashboard'
    resources :products
  end
  devise_for :users
  root 'main#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.has_role? :admin
        can :manage, :all
    else
        can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_type
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  before_save :set_display_name

  private

  def set_display_name
    self.display_name = name.titleize
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :birthdate,   presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_access!
  layout "admin"

  protected

  def verify_access!
    authorized_users = User.with_any_role :admin, :manager
    unless authorized_users.include? current_user
      render status: 500
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: { error: "You don't have access!" }, status: 403 }
      end
    end
  end
end

app/controllers/admin/main_controller.rb
class Admin::MainController < Admin::BaseController
  def dashboard
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
    @page_title = "Products"
    @products = Product.all
  end

  def new
    @page_title = "Add a Product"
    @product = Product.new
  end

  def create
    @product = Product.new product_params

    respond_to do |format|

      if @product.save
        format.html {}
        format.json {}
      else
        format.html { render :new }
        format.json { render json: { errors: @product.errors }}
      end

    end
  end

  protected

  def product_params
    params.require(:product).permit(:name, :description)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include IconicHelper
  
  def body_classes
    "#{params[:controller].gsub('/', ' ')} #{params[:action]}"
  end

  def wrapper_classes
    case @container_style
    when :static
      style = "container"
    when :fluid
      style = "container-fluid"
    when :full
      style = nil
    else
      style = "container"
    end
    ["wrapper", style].join(" ")
  end
end

app/helpers/iconic_helper.rb
module IconicHelper
  def iconic(file, options = {})
    class_names = %w{iconic}
    # unless options[:sizes].empty?
    #   options[:sizes].each do |size|
    #     class_names << "iconic-#{size}"
    #   end
    # end
    content_tag   :img, "",
                  class: class_names,
                  data: { src:  asset_path("icons/smart/#{file}.svg") }
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/main/dashboard.html.erb
<h1>URBO Dashboard</h1>

app/views/admin/products/_form.html.erb
<%= form_for @product, url: admin_products_path, layout: :basic do |f| %>
  <%= f.text_field :name %>
  <%= f.select :product_type, ProductType.all.collect{|t| [t.display_name, t.id] } %>
  <%= f.text_area :description %>
  <%= f.submit "Save Product" %>
<% end %>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.active %></td>
</tr>

app/views/admin/products/index.html.erb
<div class="page-header">
  <h1>Products</h1>
</div>

<% if @products.empty? %>

  <p class="lead">No products yet! <%= link_to "Create one now.", new_admin_product_path %></p>

<% else %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Product</th>
        <th>Active</th>
      </tr>
    </thead>
    <tbody>
      <%= render @products %>
    </tbody>
  </table>

<% end %>

app/views/admin/products/new.html.erb
<div class="page-header">
  <h1>Add a Product</h1>
</div>

<%= render "form" %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? "#{@page_title} | URBO Office" : "URBO Office" %></title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= render "shared/scripts" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="admin-layout <%= body_classes %>">

<%= render "shared/admin_navbar" %>

<div class="sidebar">
  <ul class="nav nav-sidebar">
    <li><%= link_to "Products", admin_products_path %></li>
  </ul>
</div>

<div class="content">
  <%= yield %>
</div>

<%= render "shared/notifications" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title or "URBO" %></title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= render "shared/scripts" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="default-layout <%= body_classes %>">
  <%= render "shared/navbar" %>

  <div class="<%= wrapper_classes %>">
    <%= yield %>
  </div>

  <%= render "shared/footer" %>

  <div id="registration-container"></div>
  <%= render "shared/notifications" %>
</body>
</html>

app/views/main/index.html.erb
<% @container_style = :full %>

<%# BEGIN JUMBOTRON %>
<div class="jumbotron text-center">
  <div class="container">
    <h1>Delivering happiness.</h1>
    <p>URBO provides safe and reliable medical marijuana delivery in the San Francisco Bay Area.</p>
    <p>
      <%= link_to("Become a Member", new_user_registration_path , :class => "btn btn-success btn-outline btn-pill btn-lg register-btn") %>
      <%= link_to("Learn More", "#", :class => "btn btn-default btn-outline btn-pill btn-lg") %>
    </p>
  </div>
</div>
<%# END JUMBOTRON %>

<%# BEGIN FEATURE BLOCKS %>
<div class="feature-blocks">
  <div class="container">

    <div class="feature-block">
      <div class="feature-block-icon">
        <%= iconic('flash') %>
      </div>
      <h3>Delivered in a Flash</h3>
      <p>Deliveries are quick, discreet and best of all, you don't even need to leave home!</p>
      <p>Check our <%= link_to("delivery hours", "#") %>.</p>
    </div>

    <div class="feature-block">
      <div class="feature-block-icon">
        <%= iconic('circle-check') %>
      </div>
      <h3>Quality Guaranteed</h3>
      <p>We stand behind our products and always guarantee the quality and quantity of your delivery.</p>
    </div>

  </div> <%# END .container %>
</div>
<%# END FEATURE BLOCKS %>

app/views/shared/_admin_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to("URBO Office", admin_path, :class => 'navbar-brand') %>
    </div>

    <div class="collapse navbar-collapse">
      <div class="navbar-right">
        <ul class="nav navbar-nav">
          <li><%= link_to("Dashboard", admin_path) %></li>
          <li><%= link_to("Main Site", root_path) %></li>
          <li><%= link_to("Profile", "#") %></li>
          <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
        </ul>
      </div>
    </div>

  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="about-blurb hidden-xs">
        <h6 class="section-header">About</h6>
        <p>URBO provides safe and reliable medical marijuana delivery in the San Francisco Bay Area.</p>
      </div>

      <div class="footer-links">
        <h6 class="section-header">Information</h6>
        <ul class="list-unstyled">
          <li><%= link_to("About URBO", "#") %></li>
          <li><%= link_to("Become a Driver", "#") %></li>
          <li><%= link_to("FAQs", "#") %></li>
          <li><%= link_to("Member Support", "#") %></li>
        </ul>
      </div>

      <div class="app-links">
        <h6 class="section-header">Mobile App</h6>
        <p><%= image_tag("app-store-badge.svg") %></p>
        <p><%= icon('android') %> URBO for Android coming soon.</p>
      </div>
    </div>
    <div class="row">
      <div class="copyright">
        <p>Copyright 2014. All rights reserved. <%= link_to("Terms", "#") %> &middot; <%= link_to("Privacy", "#") %></p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to("URBO", root_url, :class => 'navbar-brand') %>
    </div>

    <div class="collapse navbar-collapse">
      <div class="navbar-right">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Order History</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Support</a></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                </li>
              </ul>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to("Menu", "#") %></li>
            <li><%= link_to("How it Works", "#") %></li>
            <li><%= link_to("Delivery Areas", "#") %></li>
            <li><%= link_to("Sign In", new_user_session_path) %></li>
          </ul>
          <%= link_to("Sign Up", new_user_registration_path, :class => 'btn btn-default btn-white btn-outline btn-pill navbar-btn register-btn') %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/shared/_notifications.html.erb
<% if alert %>
  <script type="text/javascript">
    toastr.error("<%= alert %>");
  </script>
<% elsif notice %>
  <script type="text/javascript">
    toastr.info("<%= notice %>");
  </script>
<% end %>

app/views/shared/_scripts.html.erb
<script src="//use.typekit.net/qqm0qor.js"></script>
<script>try{Typekit.load();}catch(e){}</script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->